<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>da88bff0-fefd-4820-a6d8-fb6b980d067a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="sources\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net" Version="3.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.8" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
